apiVersion: apps/v1
kind: Deployment
metadata:
  name: "$name-deployment"
  labels:
    app: "$name"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "$name"
  template:
    metadata:
      labels:
        app: "$name"
    spec:
      containers:
      - name: "$name"
        image: "$image"
        ports:
        - containerPort: 80
